name = "file-zipper"
main = "src/index.ts"
compatibility_date = "2025-08-15"
workers_dev = true

# -----------------------------
# DEV ENVIRONMENT
# -----------------------------
[env.dev]
name = "file-zipper-dev"

# R2
[[env.dev.r2_buckets]]
binding = "SOURCE_BUCKET"
bucket_name = "moretransfer-dev"

[[env.dev.r2_buckets]]
binding = "OUTPUT_BUCKET"
bucket_name = "moretransfer-dev"

# Queues
[[env.dev.queues.consumers]]
queue = "moretransfer-file-zipper-dev"
max_batch_size = 1
max_retries = 3
dead_letter_queue = "moretransfer-file-zipper-dev-dlq"

[[env.dev.queues.producers]]
binding = "QUEUE_FILE_ZIPPER"
queue = "moretransfer-file-zipper-dev"

# Durable Objects
[[env.dev.durable_objects.bindings]]
name = "ZipLocks"
class_name = "ZipLocksDO"

# Vars
[env.dev.vars]
SECRET_KEY = ""
WEB_API_BASE_URL = "http://localhost:3000"
ZIP_OUTPUT_PREFIX = "bundle"
ZIP_OUTPUT_FILE_NAME = "moretransfer_bundle"
MAX_FILES = "500"
BASE_RETRY_DELAY_SECONDS = 30
MAX_ZIP_BYTES = "524288000"

# DO migrations (per env)
[[env.dev.migrations]]
tag = "v1"
new_classes = ["ZipLocksDO"]

# -----------------------------
# PROD ENVIRONMENT
# -----------------------------
[env.prod]
name = "moretransfer-file-zipper-prod"

# [[env.prod.routes]]
# pattern = "shop.example.com"
# custom_domain = true

# R2
[[env.prod.r2_buckets]]
binding = "SOURCE_BUCKET"
bucket_name = "moretransfer-storage"

[[env.prod.r2_buckets]]
binding = "OUTPUT_BUCKET"
bucket_name = "moretransfer-storage"

# Queues
[[env.prod.queues.consumers]]
queue = "moretransfer-file-zipper"
max_batch_size = 1
max_retries = 3
dead_letter_queue = "moretransfer-file-zipper-dlq"

[[env.prod.queues.producers]]
binding = "QUEUE_FILE_ZIPPER"
queue = "moretransfer-file-zipper"

# Durable Objects
[[env.prod.durable_objects.bindings]]
name = "ZipLocks"
class_name = "ZipLocksDO"

# Logging and Observability
[observability]
enabled = true
head_sampling_rate = 1

[limits]
cpu_ms = 300_000

# Vars
[env.prod.vars]
# SECRET_KEY = "" // Will be set from Secrets
WEB_API_BASE_URL = "https://moretransfer.com"
BASE_RETRY_DELAY_SECONDS = 30
ZIP_OUTPUT_PREFIX = "bundle"
ZIP_OUTPUT_FILE_NAME = "moretransfer_bundle"
MAX_FILES = "500"
MAX_ZIP_BYTES = "3145728000" # 3GB

# DO migrations (per env)
[[env.prod.migrations]]
tag = "v1"
new_classes = ["ZipLocksDO"]
